language: node_js
node_js:
- 12
branches:
  only:
  - master
cache:
  directories:
  - "$HOME/gcloud/"
  - node_modules
env:
  matrix:
  - PATH=$PATH:$HOME/gcloud/google-cloud-sdk/bin GOOGLE_APPLICATION_CREDENTIALS=$TRAVIS_BUILD_DIR/.gcloud-travis.json
before_install:
- openssl aes-256-cbc -K $encrypted_3c84dcdc6bbe_key -iv $encrypted_3c84dcdc6bbe_iv -in .env.enc -out .env -d
- openssl aes-256-cbc -K $encrypted_5c84bd10fb39_key -iv $encrypted_5c84bd10fb39_iv -in .gcloud-travis.json.enc -out .gcloud-travis.json -d
- export CLOUD_SDK_REPO="cloud-sdk-$(lsb_release -c -s)" && echo "deb http://packages.cloud.google.com/apt
  $CLOUD_SDK_REPO main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
  && curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add
  - && sudo apt-get update -y && sudo apt-get install google-cloud-sdk=216.0.0-0 -y
- if [ -a .gcloud-travis.json ]; then gcloud -q auth activate-service-account --key-file
  .gcloud-travis.json; fi
script:
- npm install
- gcloud functions deploy api --runtime nodejs12 --trigger-http --project devevents
  --verbosity=debug --memory=1024MB --timeout=30s
